### ISSUE TITLE
Problems with executing strmqm / endmqm in RDQM cluster. 

### ISSUE THREAD

**Issue by gordo1337** [ibm-client-engineering/sadoc-mq-rdqm-hadr#17]
### Issue Type

Build/Install

### Description

 have installed the new MQ RDQM HA cluster on 3-noed we got a problem with our MQM user in linux. 
We cant execute the strmqm and endmqm in /opt/mqm/bin and when trying to execute them we get the error: AMQ7077E: You are not authorized to perform the requested operation.
The Queue manager starts automatic thru RDQM and it runs under mqm-user but regardless the endmqm and strm mqm etc comes back with auth errors.. we have checked the auths on /opt/mqm anv do not see any differnce from working non RDMQ installation

The mqm user info : 
cat /etc/passwd | grep mqm
mqm:x:990:1009::/home/mqm:/bin/bash 

cat /etc/group | grep mqm
mqm:x:1009:

### Expected outcome vs. Actual Outcome

Cant execute some files in /opt/mqm/bin with mqm user.

**Comment by gordo1337** [comment]
I found the problem: 
1. semanage permissive -a drbd_t  
2. https://www.ibm.com/docs/en/ibm-mq/9.3?topic=varmqm-mq-file-permissions-in-optmqm-setuid-mqm 

cd /opt/mqm/bin/security  

 

chmod --silent -R 4550 amqo*  

 

-------------------------------------- 

 

cd /opt/mqm/bin 

 

chmod --silent -R 6550 addmqinf  

 

 

chmod --silent -R 6550 amqcrsta 

 

 

chmod --silent -R 6550 amqfcxba 

after this everything worked.

**Comment by gordo1337** [comment]
I also found something that was a bit irretating, the compability for IBM Web Console and RDQM. 
I raised an IBM ticket about the problem. 
And it seems like there is no official solution. 

(IBM Case) 
Case number

TS011981789

**Comment by faraz** [comment]
@gordo1337 

Glad everything is working. Sounds like you ran into SELinux issues. We will update this solution document with your feedback. 

While, we can't comment on support cases. I'd encourage you to reach out to your IBM rep. and ask for [IBM Client Engineering's ](https://www.ibm.com/client-engineering) to help you in your journey. IBM Client Engineering is a no-cost investment into our customers to help you solve the challenges you might be facing, using IBM Technology.

**Comment by kriahna-22** [comment]
match the mqm uid and gid to all the servers 
1009:1009 and execute the command using sudo crtmqm for rdqm  you need sudo preveliage to create or delete QM
